apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: sorton-flask

  name: sorton-flask

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sorton-flask

  template:
    metadata:
      labels:
        app: sorton-flask

    spec:
      containers:
        - name: sorton-flask

          image: europe-west2-docker.pkg.dev/apt-rite-449810-c0/container-images/flask-demo-app:latest

          ports:
            - containerPort: 8080

---
apiVersion: v1

kind: Service

metadata:
  name: sorton-flask
  namespace: sorton-flask

  labels:
    app: sorton-flask

spec:
  ports:
    - name: http

      port: 8080
      targetPort: 8080

  selector:
    app: sorton-flask

  type: LoadBalancer
