apiVersion: v1
kind: Namespace
metadata:
  name: sorton-flask
  labels:
    name: sorton-flask
---
apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: sorton-flask-app
  name: sorton-flask-app
  namespace: sorton-flask

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sorton-flask-app

  template:
    metadata:
      labels:
        app: sorton-flask-app

    spec:
      containers:
        - name: sorton-flask-container

          image: europe-west2-docker.pkg.dev/apt-rite-449810-c0/container-images/flask-demo-app:latest

          ports:
            - containerPort: 8080

---
# apiVersion: v1

# kind: Service

# metadata:
#   name: sorton-flask-app
#   namespace: sorton-flask

#   labels:
#     app: sorton-flask-app

# spec:
#   ports:
#     - name: http

#       port: 443
#       targetPort: 8080

#   selector:
#     app: sorton-flask-app

#   type: LoadBalancer
