name: Push to Artifact Registry

on: [workflow_dispatch]

env:
  IMAGE_NAME: "flask-demo-app"

jobs:
  build-and-deploy:
    name: Build Image and Deploy to Google Artifact Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Google Authenticate
        id: google-auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{secrets.GOOGLE_CREDENTIALS}}"

      - name: Docker Authenticate
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: "${{secrets.GOOGLE_CREDENTIALS}}"

      - name: Build Container
        run: docker build -t "${{ vars.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./

      - name: Push Container to Registry
        run: docker push "${{ vars.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
